name: Python Tests and PEP8 Check

# Цей GitHub Action буде запускатися при кожному push або pull request в гілку main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Тестування коду
  test:
    runs-on: ubuntu-latest
    steps:
      # Крок 1: Checkout репозиторію
      - name: Checkout code
        uses: actions/checkout@v2

      # Крок 2: Встановлення Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Можна змінити версію Python на ту, яка вам потрібна

      # Крок 3: Встановлення залежностей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Крок 4: Запуск тестів
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

  # Перевірка на відповідність PEP8
  pep8:
    runs-on: ubuntu-latest
    steps:
      # Крок 1: Checkout репозиторію
      - name: Checkout code
        uses: actions/checkout@v2

      # Крок 2: Встановлення Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Можна змінити версію Python на ту, яка вам потрібна

      # Крок 3: Встановлення залежностей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Крок 4: Встановлення flake8 для перевірки PEP8
      - name: Install flake8
        run: pip install flake8

      # Крок 5: Запуск перевірки коду на відповідність PEP8
      - name: Run flake8
        run: flake8 .
